name: CI / CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Lint with flake8
        run: flake8 . --count --show-source --statistics

      - name: Check formatting with black
        run: black --check .

      - name: Scan for code vulnerabilities with Bandit
        run: bandit -r .

      - name: Scan for dependency vulnerabilities with pip-audit
        run: pip-audit

      - name: Run tests and generate coverage report
        run: pytest --cov=modules --cov=zone_poker --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          # The Codecov token is optional for public repositories.
          # For private repos, set the CODECOV_TOKEN secret in your repository settings.
          # token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true # Fail the build if Codecov upload fails

  build-and-push-docker:
    needs: lint-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        # This step is skipped for pull requests
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/zone-poker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for scanning
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          # Do not push, just load the image into the local Docker daemon
          load: true
          tags: ghcr.io/${{ github.repository_owner }}/zone-poker:ci-scan

      - name: Scan container image for vulnerabilities with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner }}/zone-poker:ci-scan'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # Push only when the event is a push to the main branch
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Enable build cache to speed up future builds
          cache-from: type=gha
          cache-to: type=gha,mode=max