#!/usr/bin/env python3
"""
Zone-Poker - WAF Detection Module
"""
from typing import Dict, Any
import httpx
import logging

logger = logging.getLogger(__name__)

# A more comprehensive dictionary of WAF fingerprints.
WAF_FINGERPRINTS = {
    "Cloudflare": {
        "headers": {"server": "cloudflare", "any": ["cf-ray", "__cfduid"]},
        "body": ["Attention Required! | Cloudflare"],
    },
    "Akamai": {
        "headers": {"server": "AkamaiGHost", "any": ["x-akamai-transformed"]},
        "body": [
            "The requested URL was rejected. Please consult with your administrator."
        ],
    },
    "AWS WAF": {
        "headers": {"server": "awselb", "any": ["x-amz-cf-id"]},
        "body": ["AWS WAF"],
    },
    "Sucuri": {
        "headers": {"server": "Sucuri/Cloudproxy", "any": ["x-sucuri-id"]},
        "body": ["Sucuri WebSite Firewall - Access Denied"],
    },
    "Imperva (Incapsula)": {
        "headers": {"any": ["x-iinfo", "x-cdn"]},
        "body": ["Request unsuccessful. Incapsula incident ID"],
    },
    "Wordfence": {
        "headers": {},
        "body": [
            "Generated by Wordfence",
            "A potentially unsafe operation has been detected",
        ],
    },
}


async def detect_waf(domain: str, timeout: int, **kwargs: Any) -> Dict[str, Any]:
    """
    Attempts to identify a Web Application Firewall by sending both benign and
    malicious-like payloads and observing the server's response for fingerprints.
    """
    waf_info: Dict[str, Any] = {"detected_waf": "None", "reason": "", "error": None}
    benign_url = f"https://{domain}"
    malicious_url = f"https://{domain}/?s=<script>alert('xss')</script>"
    headers = {"User-Agent": "Zone-Poker WAF Detector/1.0"}

    try:
        async with httpx.AsyncClient(
            timeout=timeout, verify=False, headers=headers
        ) as client:
            # 1. Send a benign request to get a baseline
            base_response = await client.get(benign_url, follow_redirects=True)
            base_headers = {k.lower(): v for k, v in base_response.headers.items()}
            base_server = base_headers.get("server", "").lower()
            base_body = base_response.text.lower()

            # 2. Check fingerprints in the benign response
            for waf_name, fp in WAF_FINGERPRINTS.items():
                if fp["headers"].get("server") in base_server:
                    waf_info["detected_waf"] = waf_name
                    waf_info["reason"] = (
                        f"Server header matched '{fp['headers']['server']}'."
                    )
                    return waf_info
                if any(h in base_headers for h in fp["headers"].get("any", [])):
                    waf_info["detected_waf"] = waf_name
                    waf_info["reason"] = (
                        "Found a characteristic WAF header in the response."
                    )
                    return waf_info
                if any(b.lower() in base_body for b in fp.get("body", [])):
                    waf_info["detected_waf"] = waf_name
                    waf_info["reason"] = "Response body contained a WAF block message."
                    return waf_info

            # 3. Send a malicious request and check for behavioral changes
            malicious_response = await client.get(malicious_url, follow_redirects=True)
            if (
                malicious_response.status_code != base_response.status_code
                and malicious_response.status_code in (403, 406, 429, 418)
            ):
                waf_info["detected_waf"] = "Generic WAF/IPS"
                waf_info["reason"] = (
                    f"Request was blocked with status {malicious_response.status_code} "
                    f"after sending a malicious payload (baseline was {base_response.status_code})."
                )
                return waf_info

    except httpx.RequestError as e:
        waf_info["error"] = f"Could not connect to the server: {type(e).__name__}"
        logger.debug(f"WAF detection failed for {domain}: {e}")
    except Exception as e:
        waf_info["error"] = f"An unexpected error occurred: {e}"
        logger.warning(f"Unexpected error in WAF detection for {domain}: {e}")

    return waf_info
